' <auto-generated>
'   This file was generated by a tool; you should avoid making direct changes.
'   Consider using 'partial classes' to extend these types
'   Input: ldiff.proto
' </auto-generated>

#Disable Warning BC40008, BC40055, IDE1006

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class ChunkProto
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "assets")> _
    Public Readonly Property Assets As New Global.System.Collections.Generic.List(Of AssetChunkProperty)

End Class

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class AssetChunkProperty
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "asset_name")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property AssetName As String = ""

    <Global.ProtoBuf.ProtoMember(2, Name := "asset_chunks")> _
    Public Readonly Property AssetChunks As New Global.System.Collections.Generic.List(Of AssetChunk)

    <Global.ProtoBuf.ProtoMember(3, Name := "asset_type")> _
    Public Property AssetType As Integer

    <Global.ProtoBuf.ProtoMember(4, Name := "asset_size")> _
    Public Property AssetSize As Long

    <Global.ProtoBuf.ProtoMember(5, Name := "asset_hash_md5")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property AssetHashMd5 As String = ""

End Class

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class AssetChunk
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "chunk_name")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property ChunkName As String = ""

    <Global.ProtoBuf.ProtoMember(2, Name := "chunk_decompressed_hash_md5")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property ChunkDecompressedHashMd5 As String = ""

    <Global.ProtoBuf.ProtoMember(3, Name := "chunk_on_file_offset")> _
    Public Property ChunkOnFileOffset As Long

    <Global.ProtoBuf.ProtoMember(4, Name := "chunk_size")> _
    Public Property ChunkSize As Long

    <Global.ProtoBuf.ProtoMember(5, Name := "chunk_size_decompressed")> _
    Public Property ChunkSizeDecompressed As Long

End Class

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class ManifestProto
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "assets")> _
    Public Readonly Property Assets As New Global.System.Collections.Generic.List(Of AssetManifestProperty)

End Class

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class AssetManifestProperty
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "asset_name")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property AssetName As String = ""

    <Global.ProtoBuf.ProtoMember(2, Name := "asset_size")> _
    Public Property AssetSize As Long

    <Global.ProtoBuf.ProtoMember(3, Name := "asset_hash_md5")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property AssetHashMd5 As String = ""

    <Global.ProtoBuf.ProtoMember(4, Name := "asset_data")> _
    Public Property AssetData As AssetManifestChunk

End Class

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class AssetManifestChunk
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "latest_asset_version")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property LatestAssetVersion As String = ""

    <Global.ProtoBuf.ProtoMember(2, Name := "assets")> _
    Public Readonly Property Assets As New Global.System.Collections.Generic.List(Of AssetManifest)

End Class

<Global.ProtoBuf.ProtoContract()> _
Partial Public Class AssetManifest
    Implements Global.ProtoBuf.IExtensible

    Private __pbn__extensionData As Global.ProtoBuf.IExtension

    Private Function GetExtensionObject(ByVal createIfMissing As Boolean) As Global.ProtoBuf.IExtension Implements Global.ProtoBuf.IExtensible.GetExtensionObject
        Return Global.ProtoBuf.Extensible.GetExtensionObject(__pbn__extensionData, createIfMissing)
    End Function

    <Global.ProtoBuf.ProtoMember(1, Name := "chunk_file_name")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property ChunkFileName As String = ""

    <Global.ProtoBuf.ProtoMember(2, Name := "chunk_file_version")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property ChunkFileVersion As String = ""

    <Global.ProtoBuf.ProtoMember(3, Name := "chunk_file_node")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property ChunkFileNode As String = ""

    <Global.ProtoBuf.ProtoMember(4, Name := "chunk_file_size")> _
    Public Property ChunkFileSize As Long

    <Global.ProtoBuf.ProtoMember(5, Name := "chunk_file_md5")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property ChunkFileMd5 As String = ""

    <Global.ProtoBuf.ProtoMember(6, Name := "hdiff_file_in_chunk_offset")> _
    Public Property HdiffFileInChunkOffset As Long

    <Global.ProtoBuf.ProtoMember(7, Name := "hdiff_file_size")> _
    Public Property HdiffFileSize As Long

    <Global.ProtoBuf.ProtoMember(8, Name := "original_file_path")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property OriginalFilePath As String = ""

    <Global.ProtoBuf.ProtoMember(9, Name := "original_file_size")> _
    Public Property OriginalFileSize As Long

    <Global.ProtoBuf.ProtoMember(10, Name := "original_file_md5")> _
    <Global.System.ComponentModel.DefaultValue("")> _
    Public Property OriginalFileMd5 As String = ""

End Class

#Enable Warning BC40008, BC40055, IDE1006

